version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calzone_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    command: sh -c "npm install && npx prisma generate && node src/index.js"
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/calzone_db"
      JWT_SECRET: "dev_jwt_secret"
      EMAIL_TOKEN_SECRET: "dev_email_secret"
      GMAIL_USER: "your@gmail.com"
      GMAIL_APP_PASSWORD: "your-app-pass"
      FRONTEND_URL: "http://localhost:5173"
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db_data:
