version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1234
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  auth-service:
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass1234
      APP_JWT_SECRET: change_this_secret
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_FROM: ""
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  crm-service:
    build:
      context: ./backend/services/crm-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/crmdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass1234
      APP_JWT_SECRET: change_this_secret
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - auth-service
      - crm-service

volumes:
  mysql-data:
