server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpass1234}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

app:
  jwt:
    secret: ${APP_JWT_SECRET:very_secret_change_me}
    expiration-ms: ${APP_JWT_EXP_MS:86400000}

# Twilio (set these env vars to enable real SMS)
TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:}
TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:}
TWILIO_FROM: ${TWILIO_FROM:}

management:
  endpoints:
    web:
      exposure:
        include: "h2-console,health,info"
